language: r
sudo: required
cache: packages
r:
    - devel

install:
    - R -e 'install.packages(c("plotly", "igraph", "knitr", "testthat"))'

# script:
#     - R CMD build --resave-data plotWikipedia
#     - R CMD check plotWikipedia.0.99.0.tar.gz
#     - R CMD install plotWikipedia.0.99.0.tar.gz
notifications:
  emails:
    - k.t.the-answer@hotmail.co.jp
  on_failure: always
os: linux
dist: trusty