language: r
sudo: false
cache: packages
r:
    - release
    - devel
script:
    - export TRAVIS_R_VERSION=3.2.4
    - export R_LIBS_USER=~/R/Library
    - export R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library
    - export _R_CHECK_CRAN_INCOMING_=false
    - export NOT_CRAN=true
    - export R_PROFILE=~/.Rprofile.site
    - R --version
    # - R CMD BUILD --resave-data plotWikipedia
    # - R CMD CHECK plotWikipedia.0.99.0.tar.gz
    # - R CMD INSTALL plotWikipedia.0.99.0.tar.gz
notifications:
  emails:
    - k.t.the-answer@hotmail.co.jp
  on_failure: always
os:
    - linux
