language: r
sudo: required
cache: packages
r:
    - devel

install:
    - R -e 'install.packages(c("plotly", "igraph", "knitr", "testthat"))'
script:
    - R -e 'library("devtools");devtools::check("plotWikipedia")'
    - R -e 'library("devtools");devtools::build("plotWikipedia")'
    - R -e 'library("devtools");devtools::install("plotWikipedia.0.99.0.tar.gz")'
notifications:
  emails:
    - k.t.the-answer@hotmail.co.jp
  on_failure: always